"""
Automated clinical report generation.

Turns a prediction + XAI explanation + patient record into a structured,
readable summary containing the EEG seizure-class probability, the EEG evidence
tier, key findings, supporting evidence and rule-based review considerations —
the "AI-based report generation module" described in the PDR. It states no
clinical severity, urgency or treatment advice. The output is meant to be
*reviewed and edited by a physician* (see the doctor validation workflow),
never used autonomously.
"""
from __future__ import annotations

import config

# Human-friendly labels for the engineered features surfaced by XAI.
FEATURE_LABELS = {
    "mean": "signal mean", "std": "signal std. deviation",
    "variance": "signal variance", "skewness": "amplitude skewness",
    "kurtosis": "amplitude kurtosis", "rms": "root-mean-square amplitude",
    "energy": "signal energy", "line_length": "waveform line length",
    "zero_cross_rate": "zero-crossing rate",
    "hjorth_activity": "Hjorth activity", "hjorth_mobility": "Hjorth mobility",
    "hjorth_complexity": "Hjorth complexity",
    "spectral_entropy": "spectral entropy",
    "delta_abs_power": "delta absolute power", "theta_abs_power": "theta absolute power",
    "alpha_abs_power": "alpha absolute power", "beta_abs_power": "beta absolute power",
    "gamma_abs_power": "gamma absolute power",
    "delta_rel_power": "delta relative power", "theta_rel_power": "theta relative power",
    "alpha_rel_power": "alpha relative power", "beta_rel_power": "beta relative power",
    "gamma_rel_power": "gamma relative power",
    "peak_to_peak": "peak-to-peak amplitude", "mean_abs": "mean absolute amplitude",
    "n_peaks": "spike/peak count", "spectral_centroid": "spectral centroid",
    "spectral_edge_90": "90% spectral edge frequency",
    "band_ratio_theta_alpha": "theta/alpha power ratio",
    "band_ratio_lowfast": "slow/fast power ratio",
    "higuchi_fd": "Higuchi fractal dimension", "katz_fd": "Katz fractal dimension",
}

# Review considerations per EEG evidence tier (decision support only).
RECOMMENDATIONS = {
    1: ["Very low seizure-class evidence in this EEG segment.",
        "A low output does not exclude epilepsy or a seizure outside this segment."],
    2: ["Low seizure-class evidence; correlate with recording quality and context."],
    3: ["Intermediate model evidence; obtain expert EEG review before interpretation.",
        "Consider a longer or repeat recording when clinically indicated."],
    4: ["High model evidence; prompt expert EEG review and clinical correlation.",
        "Check for artifact and compare with video/semiology when available."],
    5: ["Very high model evidence that this EEG segment is ictal.",
        "Prompt expert review is appropriate; emergency treatment must depend on "
        "the observed condition, event duration, and clinical protocol — never on "
        "this tier alone."],
}

DISCLAIMER = (
    "This report is generated by an automated clinical DECISION-SUPPORT system and is "
    "intended to assist, not replace, a qualified physician. The evidence tier "
    "uses EEG only. Supplemental modalities are contextual and are not model "
    "inputs unless a future report explicitly states otherwise. The five-level "
    "grade is a calibrated-probability tier, not a validated clinical seizure-"
    "severity scale. Final diagnosis and treatment decisions rest with the "
    "reviewing clinician."
)


def _label(feature: str) -> str:
    return FEATURE_LABELS.get(feature, feature)


# ASCII only: this block is embedded verbatim in the latin-1 PDF export, where
# an em dash would degrade to "?" in the middle of the warning.
SYNTHETIC_WATERMARK = [
    "*" * 68,
    "**  SYNTHETIC COMPOSITE - NOT A REAL PATIENT                      **",
    "**                                                                **",
    "**  Assembled from unrelated public cohorts for demonstration.    **",
    "**  No individual has all of the findings below. Every signal is  **",
    "**  a real recording, but they do not all belong to one person.   **",
    "**  See the DATA PROVENANCE section for the source of each item.  **",
    "*" * 68,
]


class _Sections:
    """Number report sections in order so optional blocks stay consistent."""

    def __init__(self):
        self.count = 0

    def __call__(self, title: str) -> str:
        self.count += 1
        return f"\n{self.count}. {title}"


def generate_report(patient: dict, prediction: dict, xai: dict) -> str:
    """Return a formatted plain-text clinical report."""
    sev = prediction["severity"]
    prob_pct = 100.0 * prediction["seizure_probability"]
    synthetic = bool(patient.get("synthetic_composite"))
    section = _Sections()
    lines = []

    lines.append("=" * 68)
    lines.append("   EPILEPSY CLINICAL DECISION SUPPORT — AUTOMATED REPORT")
    lines.append("=" * 68)

    # -- Patient summary
    lines.append(section("PATIENT SUMMARY"))
    lines.append(f"   Patient ID   : {patient.get('patient_id', patient.get('index', 'N/A'))}")
    lines.append(f"   Name         : {patient.get('name', 'N/A')}")
    value = lambda key: patient.get(key) if patient.get(key) not in (None, "") else "Not provided"
    lines.append(f"   Age / Sex    : {value('age')} / {value('sex')}")
    lines.append(f"   Heart rate   : {value('heart_rate_bpm')} (context; not model input)")
    lines.append(f"   Medication   : {value('medication')}")
    lines.append(f"   History      : {value('medical_history')}")
    lines.append(f"   Daily routine: {value('daily_routine')}")
    lines.append(f"   MRI          : {value('mri_impression')}")
    lines.append(f"   X-ray        : {value('xray_impression')}")

    # -- EEG seizure-class probability
    lines.append(section("EEG SEIZURE-CLASS PROBABILITY"))
    lines.append(f"   Model        : {prediction.get('model_name', 'N/A')} "
                 f"(EEG source: {prediction.get('data_source', 'N/A')})")
    lines.append("   Model inputs : EEG only")
    lines.append(f"   Prediction   : {prediction['prediction_label']}")
    lines.append(f"   Probability  : {prob_pct:.1f}% EEG segment seizure-class "
                 f"probability (calibrated)")
    if prediction.get("decision_threshold") is not None:
        policy = ("sensitivity-first" if prediction.get("operating_point") == "sensitivity"
                  else "maximum balanced accuracy")
        lines.append(f"   Decision     : positive at >= "
                     f"{100.0 * prediction['decision_threshold']:.1f}% "
                     f"({policy} operating point)")

    # -- EEG evidence tier
    lines.append(section("EEG EVIDENCE TIER"))
    lines.append(f"   Level {sev['level']} - {sev['label'].upper()}  "
                 f"(probability-tier score {sev['score']:.2f})")
    lines.append(f"   Basis        : seizure probability {sev['seizure_probability']:.2f}")
    lines.append(f"   EEG intensity: {sev['intensity']:.2f} "
                 "(context only; does not change tier)")

    composite = prediction.get("composite_severity")
    if composite:
        lines.append(section("COMPOSITE CLINICAL SEVERITY  (multi-modal)"))
        lines.append(f"   Level {composite['level']} - "
                     f"{composite['label'].upper()}  "
                     f"(score {composite['score']:.2f} of "
                     f"{composite['max_score']:.2f})")
        lines.append("   Every term below is an itemised rule, not a model "
                     "output:")
        for term in composite["terms"]:
            marker = " " if term["available"] else "?"
            lines.append(f"   {marker} {term['label']:<32} "
                         f"{term['points']:+.2f} / {term['max_points']:.2f}")
            for chunk in _wrap(term["detail"], 58):
                lines.append(f"        {chunk}")
        if composite.get("missing_inputs"):
            lines.append("   ? = input unavailable; term scored zero, so this "
                         "grade is a")
            lines.append("       floor rather than a reassuring result.")
        for chunk in _wrap(composite["caveat"], 62):
            lines.append(f"   {chunk}")

    # -- Key findings (top XAI features)
    lines.append(section("KEY FINDINGS  (most influential EEG features)"))
    for f in xai.get("top_features", []):
        arrow = {"increases": "^", "decreases": "v"}.get(
            f["direction"], "-")
        lines.append(f"   {arrow} {_label(f['feature']):<28} value={f['value']:>10.3f}  "
                     f"({f['direction']} seizure likelihood)")

    # -- Supporting evidence
    lines.append(section("SUPPORTING EVIDENCE"))
    lines.append(f"   Explanation method: {xai.get('method', 'N/A')}")
    lines.append("   The features above were the largest contributors to this "
                 "prediction,")
    lines.append("   ranked by their local attribution magnitude.")

    # -- Recommendations
    lines.append(section("REVIEW CONSIDERATIONS  (decision support only)"))
    for rec in RECOMMENDATIONS.get(sev["level"], []):
        lines.append(f"   - {rec}")

    # -- Disclaimer
    lines.append(section("DISCLAIMER"))
    for chunk in _wrap(DISCLAIMER, 64):
        lines.append(f"   {chunk}")

    lines.append("\n" + "=" * 68)
    return "\n".join(lines)


def _wrap(text: str, width: int):
    words, line, out = text.split(), "", []
    for w in words:
        if len(line) + len(w) + 1 > width:
            out.append(line)
            line = w
        else:
            line = f"{line} {w}".strip()
    if line:
        out.append(line)
    return out


def build_full_result(patient: dict, segment) -> dict:
    """Convenience: run prediction + XAI + report for one segment."""
    from src.explainability.xai import explain
    from src.models.inference import predict_segment

    prediction = predict_segment(segment)
    xai = explain(prediction["feature_vector"])
    report = generate_report(patient, prediction, xai)
    # Drop the raw numpy vector before returning a JSON-friendly result
    pred_clean = {k: v for k, v in prediction.items() if k != "feature_vector"}
    return {"prediction": pred_clean, "xai": xai, "report": report}
